package br.maua.cic303;

import java_cup.runtime.Symbol;

parser code {:
    public void syntax_error(Symbol cur_token) {
        throw new Error("Erro sintático");
    }
:};

terminal IF, THEN, ELSE, WHILE;
terminal PLUS, MINUS, TIMES, DIV, MOD;
terminal ASSIGN;
terminal EQ, NE, GT, LT, GE, LE;
terminal LPAREN, RPAREN, LBRACE, RBRACE, SEMI;

terminal String ID;
terminal Integer NUMBER;

non terminal program;
non terminal lista_comandos;
non terminal comando;
non terminal bloco;
non terminal expressao;

precedence right ELSE;
precedence left EQ, NE, GT, LT, GE, LE;
precedence left PLUS, MINUS;
precedence left TIMES, DIV, MOD;

start with program;

program ::=
    lista_comandos
;

lista_comandos ::=
      lista_comandos comando
    | comando
    |
;

comando ::=
      ID ASSIGN expressao SEMI
    | IF LPAREN expressao RPAREN THEN bloco
    | IF LPAREN expressao RPAREN THEN bloco ELSE bloco
    | WHILE LPAREN expressao RPAREN bloco
    | bloco
    | SEMI
;

bloco ::=
      LBRACE lista_comandos RBRACE
;

expressao ::=
      expressao PLUS expressao
    | expressao MINUS expressao
    | expressao TIMES expressao
    | expressao DIV expressao
    | expressao MOD expressao

    | expressao EQ expressao
    | expressao NE expressao
    | expressao GT expressao
    | expressao LT expressao
    | expressao GE expressao
    | expressao LE expressao

    | LPAREN expressao RPAREN
    | ID
    | NUMBER
;