package br.maua.cic303;

import java_cup.runtime.*;

parser code {:
    public void syntax_error(Symbol cur_token) {
        throw new RuntimeException(
            "Erro Sintático"
        );
    }
:};

/* TERMINAIS */
terminal IF, THEN, ELSE, WHILE;
terminal ASSIGN, LPAREN, RPAREN, LBRACE, RBRACE, SEMI;
terminal EOF;

terminal String ID;
terminal Integer NUMBER;

terminal String ADD_OP;
terminal String MUL_OP;
terminal String REL_OP;

/* NÃO TERMINAIS */
non terminal program;
non terminal stmt_list;
non terminal stmt;
non terminal expr;

/* PRECEDÊNCIA */
precedence left REL_OP;
precedence left ADD_OP;
precedence left MUL_OP;

start with program;

/* GRAMÁTICA */

program ::= stmt_list EOF ;

stmt_list ::= stmt_list stmt
            | stmt
            | /* vazio */
            ;

stmt ::= ID ASSIGN expr SEMI
       | IF LPAREN expr RPAREN THEN stmt
       | IF LPAREN expr RPAREN THEN stmt ELSE stmt
       | WHILE LPAREN expr RPAREN stmt
       | LBRACE stmt_list RBRACE
       | SEMI
       ;

expr ::= expr ADD_OP expr
       | expr MUL_OP expr
       | expr REL_OP expr
       | LPAREN expr RPAREN
       | NUMBER
       | ID
       ;