package br.maua.cic303;

import java_cup.runtime.*;

parser code {:
    public void syntax_error(Symbol cur_token) {
        throw new RuntimeException("Erro Sintático");
    }
:};

terminal IF, THEN, ELSE, WHILE;

terminal ASSIGN;

terminal LPAREN, RPAREN;
terminal LBRACE, RBRACE;

terminal SEMI;

terminal PLUS, MINUS;
terminal TIMES, DIV, MOD;

terminal EQ, NE, LT, GT, LE, GE;

terminal String ID;
terminal String NUMBER;

non terminal program;
non terminal stmt_list;
non terminal stmt;
non terminal expr;

precedence left EQ, NE, LT, GT, LE, GE;
precedence left PLUS, MINUS;
precedence left TIMES, DIV, MOD;

start with program;

program ::= stmt_list ;

stmt_list ::= stmt_list stmt
            | stmt
            ;

stmt ::= ID ASSIGN expr SEMI
       | IF LPAREN expr RPAREN THEN stmt
       | IF LPAREN expr RPAREN THEN stmt ELSE stmt
       | WHILE LPAREN expr RPAREN stmt
       | LBRACE stmt_list RBRACE
       | LBRACE RBRACE
       | SEMI
       ;

expr ::= expr PLUS expr
       | expr MINUS expr
       | expr TIMES expr
       | expr DIV expr
       | expr MOD expr
       | expr EQ expr
       | expr NE expr
       | expr LT expr
       | expr GT expr
       | expr LE expr
       | expr GE expr
       | LPAREN expr RPAREN
       | NUMBER
       | ID
       ;